name: eventy
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  dotted_border: ^2.1.0
  dotted_line: ^3.2.2
  floating_navbar: ^2.0.2
  flutter:
    sdk: flutter
  flutter_floating_bottom_bar: ^1.2.0
  flutter_typeahead: ^4.8.0
  get: ^4.6.6
  ionicons: ^0.2.2
  pretty_qr_code: ^3.0.0
  provider: ^6.1.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
  - assets/images/profile.jpg
  - assets/images/UIUXEvent.jpg
  - assets/images/gamingEvent.jpg
  - assets/images/quantumEvent.jpg
  - assets/images/logo.png
  - assets/icon/icon.png
icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png
