// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEiB8zpq-JT9rWQpYcPQg0ObTFc3BrWEI',
    appId: '1:788332000930:web:6626320cd3c42c49b749fb',
    messagingSenderId: '788332000930',
    projectId: 'eventy-b8233',
    authDomain: 'eventy-b8233.firebaseapp.com',
    storageBucket: 'eventy-b8233.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdalXXFZe6DKf9RXSOaiP4E1OAs-6kYhQ',
    appId: '1:788332000930:android:318e64405932a3a2b749fb',
    messagingSenderId: '788332000930',
    projectId: 'eventy-b8233',
    storageBucket: 'eventy-b8233.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW5AweIBAJ4j_vkbJEtfblyYeIFuSp_48',
    appId: '1:788332000930:ios:7ed97c79c5e3a256b749fb',
    messagingSenderId: '788332000930',
    projectId: 'eventy-b8233',
    storageBucket: 'eventy-b8233.appspot.com',
    iosBundleId: 'com.example.eventy1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW5AweIBAJ4j_vkbJEtfblyYeIFuSp_48',
    appId: '1:788332000930:ios:61fb049b8443bf38b749fb',
    messagingSenderId: '788332000930',
    projectId: 'eventy-b8233',
    storageBucket: 'eventy-b8233.appspot.com',
    iosBundleId: 'com.example.eventy1.RunnerTests',
  );
}
